import "../Styles/main.scss";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main">
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
